require 'yaml'

version = YAML.load_file ARGV[0]

version['string'] = 'release' unless version.has_key?('string')

File.open(ARGV[1], 'w') do |f|
  f.puts "/* xia_version.h -- AUTOGENERATED"
  f.puts " *"
  f.puts " * Generated by gen_version.rb on #{DateTime.now.to_s}"
  f.puts " */"
  f.puts
  f.puts "#ifndef XIA_VERSION_H"
  f.puts "#define XIA_VERSION_H"
  f.puts
  f.puts "#define XERXES_MAJOR_VERSION #{version['major']}"
  f.puts "#define XERXES_MINOR_VERSION #{version['minor']}"
  f.puts "#define XERXES_RELEASE_VERSION #{version['revision']}"
  f.puts
  f.puts "#define HANDEL_MAJOR_VERSION #{version['major']}"
  f.puts "#define HANDEL_MINOR_VERSION #{version['minor']}"
  f.puts "#define HANDEL_RELEASE_VERSION #{version['revision']}"
  f.puts
  f.puts "#define VERSION_STRING \"#{version['string']}\""
  f.puts
  f.puts "#endif /* __XIA_VERSION_H__ */"
  f.puts
end
