/* xia_version.h -- AUTOGENERATED
 *
 * Generated by gen_version.rb on 2021-11-16T15:35:18-08:00
 */

#ifndef XIA_VERSION_H
#define XIA_VERSION_H

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 1
#define XERXES_RELEASE_VERSION 22

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 1
#define HANDEL_RELEASE_VERSION 22

#define VERSION_STRING "4e5006cc"

#endif /* __XIA_VERSION_H__ */

