/* xia_version.h -- AUTOGENERATED
 *
 * Generated by gen_version.rb on 2017-07-21T12:24:10-04:00
 */

#ifndef XIA_VERSION_H
#define XIA_VERSION_H

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 1
#define XERXES_RELEASE_VERSION 15

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 1
#define HANDEL_RELEASE_VERSION 15

#define VERSION_STRING "9e69fad018a4"

#endif /* __XIA_VERSION_H__ */

